site_name: FastAPI Sphere
theme:
  name: material
  font:
    text: Noto Sans Japanese
    code: Fira Code
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: teal
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.sections
    - navigation.path
    - navigation.footer
  icon:
    repo: fontawesome/brands/github-alt
  repo_name: shota-nukumizu/fastapi-sphere
  repo_url: https://github.com/shota-nukumizu/fastapi-sphere
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - toc:
      permalink: true
  - pymdownx.superfences

